apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  # name: letsencrypt-staging # 테스트용.
  name: letsencrypt # 실제 운영용.
spec:
  acme:
    email: redsubmarine@yahoo.com
    # server: https://acme-staging-v02.api.letsencrypt.org/directory # 테스트용.
    server: https://acme-v02.api.letsencrypt.org/directory # 실제 운영용.
    privateKeySecretRef:
      name: letsencrypt-account-private-key
    solvers:
    - http01:
        ingress:
          class: nginx